### ISSUE TITLE
References table view and reference detail view

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#159]
As part of #109 we need to revisit the references list to be a table view. We also need to consider a reference detail view where we display all known metadata about a reference and allow the user to edit metadata. Metadata includes both scholarly metadata as well as application metadata such as whether we have the PDF, whether GROBID is parsing or was able to parse metadata, whether the PDF contents are available for chat, etc.

Let's collect screenshots and sketches of the potential UX for each of these components here.

At a high level we discussed whether the references table view should be in the left sidebar where it currently resides or if it might be better handled by a "terminal view" that comes up from the bottom.

For the reference detail view, we discussed either having a collapsible section drop down below a reference in the table when it is clicked or opening up an editor window to view details for an individual reference.

---
Tasks (added by @cguedes) after meeting

- [x] "List view" of many references in left sidebar: list view with sort, filter, add, export functionality at the top (#202)
- [x] "Table view" of many references in editor area: full table with add/remove columns, sort/filter/tag/organize, bulk modifications, etc. (#200, #201)
- [x] "Detail view" of one reference in editor area: edit metadata for a single reference. In the future: add notes, full text, tags, etc. ( #182,  #199)

**Comment by hammer** [comment]
Here's how Zotero does it. They have a simple table layout with very few default columns. New columns can be added by right-clicking on the column names and selecting more. Sorting can be done by clicking a column, and a secondary sort column can be set by right-clicking a column title.

There are two layout options for the reference detail view: the standard view puts the details to the right of the table, and the stacked view puts them to the bottom. Within the detail view, there's a standard form with fields to edit, and a set of tabs for notes, tags, and related references. Note that related references are manually added by the user.

<img width="1470" alt="Screenshot 2023-06-16 at 1 39 19 PM" src="https://github.com/refstudio/refstudio/assets/15233/c3054cda-d9a9-40ee-ae06-218cf94a5cfd">
<img width="1470" alt="Screenshot 2023-06-16 at 1 39 08 PM" src="https://github.com/refstudio/refstudio/assets/15233/ee53af3e-69c8-4efa-bbda-0fd11b2cd098">

**Comment by hammer** [comment]
### Papers

Similar to Zotero with left sidebar for folders and table in the main pane. Interestingly, they have a search bar at the top of the table, with a non-trivial [search syntax](https://support.papersapp.com/support/solutions/articles/30000037532-advanced-searching-in-library-). @danvk will probably anticipate that I'll want to have some kind of [JQL-like search language](https://github.com/hammerlab/cycledash/pull/193) for references someday too based on the [Cycledash](https://github.com/hammerlab/cycledash) experience.

When you click a reference in the table a detail view opens in the right sidebar with similar features to the sidebar in Zotero. In this case, the info tab does not allow editing by default, and the tabs are accessed with icons rather than labeled buttons. Tabs are: Info, Edit, Notes, Files, Export. Another search-related feature: author names in the detail view (blue text) are links to author searches over your reference library.

<img width="1470" alt="Screenshot 2023-06-19 at 8 51 37 AM" src="https://github.com/refstudio/refstudio/assets/15233/c771c749-56fd-44f5-8a73-637c91993235">

**Comment by hammer** [comment]
### EndNote

Nothing much new to report with EndNote, it uses the same left, center, and right sidebar mix, with a few tweaks. The most interesting feature I have found is the ability to search public reference databases from the same search bar that can be used for your local reference database, as demonstrated in the video. [How to Use EndNote in 5 Minutes: Windows](https://www.youtube.com/watch?v=S3xo6ZjBV6U).

<img width="1470" alt="Screenshot 2023-06-19 at 9 38 28 AM" src="https://github.com/refstudio/refstudio/assets/15233/1addf0f4-3578-489b-b652-f0fe6271f925">

**Comment by hammer** [comment]
@cguedes @sehyod How are y'all feeling about implementing the table view in the left sidebar versus in the footer (where the Terminal is found in VS Code, with the option to make it full screen)? A simple table should be okay in the sidebar but if we add search and the ability to add more columns to the table it could get crowded. If references are in the left sidebar of Ref Studio it's also hard to squeeze in the left sidebar from the table view in the screenshots above, where references can be organized into folders. We can always leave that feature out for now and see how things go.

At a high level I'm starting to wonder if AI interactions should be in the left sidebar and references should be in the footer to simplify things. It's a big change though and perhaps we should wait until after this initial 3 month sprint to evaluate it...

**Comment by cguedes** [comment]
@hammer I agree that a table in the left sidebar (with extras like search, ...) would be crowed as you say. 

I think that we should make the left panel a references list (maybe a tree in the future) with a search filter and actions for each item, and build a central pane to display the references in a table view with extended functionality (still not sure about the master/detail UX to show details of a reference).

![image](https://github.com/refstudio/refstudio/assets/174127/75d1c7d5-641b-4672-b95e-b1a8f68ad484)

This is related to #174

**Comment by hammer** [comment]
@cguedes thanks for the input! I'm willing to see what the references table with search and status icons would look like in the current location of the left sidebar. I think another solution is to allow an expanded table view to open within the editor area.

For the reference detail view for a single reference, I think your idea of having it in the editor area is a good one.

**Comment by hammer** [comment]
In this week's developer call, we discussed there being 3 separate views for reference metadata:

1. "List view" of many references in left sidebar: list view with sort, filter, add, export functionality at the top
2. "Table view" of many references in editor area: full table with add/remove columns, sort/filter/tag/organize, bulk modifications, etc.
3. "Detail view" of one reference in editor area: edit metadata for a single reference. In the future: add notes, full text, tags, etc.

**Comment by cguedes** [comment]
Closing this as all the tasks are completed.
